import io
import json
import logging
import math
import os
from typing import Literal

import PIL.Image
from dotenv import load_dotenv
from google import genai
from google.genai import types
from pydantic import BaseModel, Field, ValidationError, field_validator

# Load environment variables
load_dotenv()

api_key = os.environ.get("GEMINI_API_KEY")
ocr_model = os.environ.get("GEMINI_OCR_MODEL", "gemini-3.1-flash-lite")
max_dimension = int(os.environ.get("GEMINI_OCR_MAX_DIMENSION", "1024"))
logger = logging.getLogger(__name__)


class OCRProcessingError(RuntimeError):
    """Raised when position recognition cannot produce a trustworthy result."""


class OCRConfigurationError(OCRProcessingError):
    """Raised when the position-recognition service is not configured."""


class InvalidImageError(OCRProcessingError):
    """Raised when uploaded bytes cannot be decoded as an image."""


class OCRPosition(BaseModel):
    qty: int = Field(description="Quantity. Positive for long, negative for short; never zero.")
    expiration: str = Field(description='Expiration date formatted as "Mon Day", for example "Jan 16".')
    # Google's typed response schema supports inclusive numeric bounds, but not
    # Pydantic's `exclusiveMinimum` generated by Field(gt=0). Keep the model-facing
    # schema compatible and enforce the strict domain rule after generation.
    strike: float = Field(description="Positive option strike price.")
    type: Literal["C", "P"] = Field(description='Option type: "C" for call or "P" for put.')

    @field_validator("qty")
    @classmethod
    def quantity_must_be_nonzero(cls, value: int) -> int:
        if value == 0:
            raise ValueError("quantity must not be zero")
        return value

    @field_validator("strike")
    @classmethod
    def strike_must_be_positive(cls, value: float) -> float:
        if not math.isfinite(value) or value <= 0:
            raise ValueError("strike must be finite and positive")
        return value


class OCRPositions(BaseModel):
    positions: list[OCRPosition]


def _prepare_image(image_bytes):
    image = PIL.Image.open(io.BytesIO(image_bytes))
    width, height = image.size

    if width > max_dimension or height > max_dimension:
        scale = max_dimension / max(width, height)
        new_width = int(width * scale)
        new_height = int(height * scale)
        image = image.resize((new_width, new_height), PIL.Image.Resampling.LANCZOS)
        print(f"Image resized from {width}x{height} to {new_width}x{new_height}")

    if image.mode not in ("RGB", "RGBA"):
        image = image.convert("RGB")

    output = io.BytesIO()
    image.save(output, format="PNG", optimize=True)
    return output.getvalue(), "image/png"


def parse_screenshot(image_bytes):
    if not api_key:
        raise OCRConfigurationError("Position recognition is not configured")

    try:
        try:
            optimized_image, mime_type = _prepare_image(image_bytes)
        except (
            PIL.UnidentifiedImageError,
            PIL.Image.DecompressionBombError,
            OSError,
            ValueError,
        ) as e:
            raise InvalidImageError(
                "The uploaded file is not a readable image"
            ) from e

        prompt = """
        Extract every option position visible in this screenshot using the provided response schema.

        Rules:
        1. Ignore "Days" (e.g. 22d).
        2. Fix common OCR errors (e.g. "Janié" -> "Jan 16", "©" -> "C").
        3. Return only positions visible in the screenshot.
        """

        with genai.Client(api_key=api_key) as client:
            response = client.models.generate_content(
                model=ocr_model,
                contents=[
                    prompt,
                    types.Part.from_bytes(data=optimized_image, mime_type=mime_type),
                ],
                config=types.GenerateContentConfig(
                    response_mime_type="application/json",
                    response_schema=OCRPositions,
                ),
            )

        text = (response.text or "").strip()
        if text.startswith("```json"):
            text = text[7:]
        if text.startswith("```"):
            text = text[3:]
        if text.endswith("```"):
            text = text[:-3]

        try:
            parsed = OCRPositions.model_validate_json(text)
        except ValidationError:
            parsed = OCRPositions.model_validate(json.loads(text))

        return [position.model_dump() for position in parsed.positions]

    except (json.JSONDecodeError, ValidationError) as e:
        logger.warning("Gemini OCR returned invalid position data: %s", e)
        raise OCRProcessingError(
            "Position recognition returned invalid data"
        ) from e
    except OCRProcessingError:
        raise
    except Exception as e:
        logger.exception("Gemini OCR request failed")
        raise OCRProcessingError("Position recognition failed") from e
